//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBlib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messagerie
    {
        public long Identifier { get; set; }
        public string Texte { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> QuiEcrit { get; set; }
        public long IdentifierUser { get; set; }
        public long IdentifierProducer { get; set; }
    
        public virtual Producer Producer { get; set; }
        public virtual User User { get; set; }
    }
}
