//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastingV2.DBlib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offer()
        {
            this.ArtistOffers = new HashSet<ArtistOffer>();
        }
    
        public long Identifier { get; set; }
        public string Name { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> PublishDateTime { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> StartContractDate { get; set; }
        public Nullable<int> PostCount { get; set; }
        public string JobDescription { get; set; }
        public string ProfilDescription { get; set; }
        public string Street { get; set; }
        public Nullable<long> IdentifierCity { get; set; }
        public Nullable<long> IdentifierProducer { get; set; }
        public Nullable<long> IdentifierJob { get; set; }
        public Nullable<long> IdentifierContractType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtistOffer> ArtistOffers { get; set; }
        public virtual City City { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual Job Job { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
